
//----------------------------------------------------
// The following code was generated by CUP v0.10j
// Wed Feb 28 19:24:39 PST 2024
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SHORT = 4;
  public static final int IDENTIFIER = 39;
  public static final int ANDEQ = 79;
  public static final int GT = 47;
  public static final int IMPLEMENTS = 28;
  public static final int NOTEQ = 60;
  public static final int PLUSEQ = 72;
  public static final int RBRACK = 91;
  public static final int COMMA = 83;
  public static final int RBRACE = 87;
  public static final int DOUBLE_LITERAL = 38;
  public static final int RPAREN = 89;
  public static final int LBRACK = 90;
  public static final int LT = 46;
  public static final int ANDAND = 64;
  public static final int OROR = 65;
  public static final int DOUBLE = 8;
  public static final int LBRACE = 86;
  public static final int LPAREN = 88;
  public static final int RRSHIFT = 68;
  public static final int XOREQ = 75;
  public static final int INTEGER_LITERAL = 40;
  public static final int NOT = 57;
  public static final int FINAL = 34;
  public static final int FLOAT = 7;
  public static final int COMP = 56;
  public static final int EQ = 45;
  public static final int MOD = 58;
  public static final int BOOLEAN_LITERAL = 36;
  public static final int CLASS = 12;
  public static final int SUPER = 21;
  public static final int ABSTRACT = 35;
  public static final int LONG = 6;
  public static final int PLUS = 52;
  public static final int LONG_LITERAL = 41;
  public static final int WHILE = 24;
  public static final int EXTENDS = 16;
  public static final int INTERFACE = 29;
  public static final int CHAR = 3;
  public static final int BOOLEAN = 9;
  public static final int SWITCH = 26;
  public static final int DO = 14;
  public static final int FOR = 17;
  public static final int RSHIFTEQ = 77;
  public static final int VOID = 23;
  public static final int DIV = 55;
  public static final int PUBLIC = 31;
  public static final int RETURN = 20;
  public static final int MULT = 54;
  public static final int ELSE = 15;
  public static final int BREAK = 11;
  public static final int GTEQ = 49;
  public static final int DOT = 84;
  public static final int INT = 5;
  public static final int NULL_LITERAL = 42;
  public static final int STRING_LITERAL = 43;
  public static final int EQEQ = 59;
  public static final int SEMICOLON = 81;
  public static final int EOF = 0;
  public static final int THIS = 22;
  public static final int DEFAULT = 27;
  public static final int MULTEQ = 70;
  public static final int IMPORT = 30;
  public static final int MINUS = 53;
  public static final int FLOAT_LITERAL = 37;
  public static final int LTEQ = 48;
  public static final int OR = 63;
  public static final int error = 1;
  public static final int DIVEQ = 71;
  public static final int LSHIFTEQ = 76;
  public static final int CONTINUE = 13;
  public static final int IF = 18;
  public static final int INSTANCEOF = 69;
  public static final int MODEQ = 74;
  public static final int MINUSMINUS = 51;
  public static final int COLON = 82;
  public static final int CHARACTER_LITERAL = 44;
  public static final int OREQ = 80;
  public static final int QUEST = 85;
  public static final int CASE = 25;
  public static final int PLUSPLUS = 50;
  public static final int NEW = 19;
  public static final int RSHIFT = 67;
  public static final int STRING = 10;
  public static final int BYTE = 2;
  public static final int AND = 61;
  public static final int PRIVATE = 32;
  public static final int STATIC = 33;
  public static final int LSHIFT = 66;
  public static final int XOR = 62;
  public static final int RRSHIFTEQ = 78;
  public static final int MINUSEQ = 73;
}

